#!/bin/bash

if [ -z "$SUBMODULES_HOME" ]; then

  echo "ERROR: The SUBMODULES_HOME is not defined"
  exit 1
fi

if [ -z "$1" ]; then

  echo "ERROR: Project path parameter not provided"
  exit 1
fi

PATH_PROJECT="$1"

if ! test -e "$PATH_PROJECT"; then

  echo "ERROR: Project at path does not exist '$PATH_PROJECT'"
  exit 1
fi

echo "Preparing project at: '$PATH_PROJECT'"

SCRIPT_PATHS="$SUBMODULES_HOME/Software-Toolkit/Utils/Sys/paths.sh"

if ! test  -e "$SCRIPT_PATHS"; then

    echo "ERROR: Prepare script not found '$SCRIPT_PATHS'"
    exit 1
fi

# shellcheck disable=SC1090
. "$SCRIPT_PATHS"

SCRIPT_LINK="$SUBMODULES_HOME/Software-Toolkit/Utils/Sys/Filesystem/link.sh"

if ! test -e "$SCRIPT_LINK"; then

  echo "ERROR: Script not found '$SCRIPT_LINK'"
  exit 1
fi

# shellcheck disable=SC1090
. "$SCRIPT_LINK"

DIR_RECIPES_ICONIC="Recipes/Iconic"
DIR_RECIPES_PROJECT="Recipes/Project"

DIR_RECIPES_ICONIC_FULL="$PATH_PROJECT/$DIR_RECIPES_ICONIC"
DIR_RECIPES_PROJECT_FULL="$PATH_PROJECT/$DIR_RECIPES_PROJECT"

DIR_RUN_TEST="Run/Test"
DIR_RUN_ICONIC="Run/Iconic"
DIR_RUN_PROJECT="Run/Project"

DIR_RUN_TEST_FULL="$PATH_PROJECT/$DIR_RUN_TEST"
DIR_RUN_ICONIC_FULL="$PATH_PROJECT/$DIR_RUN_ICONIC"
DIR_RUN_PROJECT_FULL="$PATH_PROJECT/$DIR_RUN_PROJECT"

INIT_DIR "$DIR_RUN_TEST_FULL"
INIT_DIR "$DIR_RUN_ICONIC_FULL"
INIT_DIR "$DIR_RUN_PROJECT_FULL"
INIT_DIR "$DIR_RECIPES_ICONIC_FULL"
INIT_DIR "$DIR_RECIPES_PROJECT_FULL"

FILE_SYNC="sync"
FILE_TEST="test"
FILE_OPEN="open"
FILE_CLONE="clone"
FILE_PREPARE="prepare"
FILE_PULL_ALL="pull_all"
FILE_PUSH_ALL="push_all"

FILE_RUN_TEST_MAIN="main.sh"
FILE_RUN_PROJECT_OPEN="open.sh"
FILE_RUN_ICONIC_ICONIFY="iconify.sh"

FILE_RECIPES_PROJECT_PRE_OPEN="pre_open.sh"
FILE_RECIPES_PROJECT_PROJECT_PRE_OPEN="project_pre_open.sh"
FILE_RECIPES_ICONIC_LAUNCHER_PARAMS="launcher_parameters.sh"

LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$FILE_SYNC" "$PATH_PROJECT/$FILE_SYNC"
LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$FILE_TEST" "$PATH_PROJECT/$FILE_TEST"
LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$FILE_OPEN" "$PATH_PROJECT/$FILE_OPEN"
LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$FILE_CLONE" "$PATH_PROJECT/$FILE_CLONE"
LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$FILE_PREPARE" "$PATH_PROJECT/$FILE_PREPARE"
LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$FILE_PULL_ALL" "$PATH_PROJECT/$FILE_PULL_ALL"
LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$FILE_PUSH_ALL" "$PATH_PROJECT/$FILE_PUSH_ALL"

LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$DIR_RECIPES_ICONIC/$FILE_RECIPES_ICONIC_LAUNCHER_PARAMS" \
  "$DIR_RECIPES_ICONIC_FULL/$FILE_RECIPES_ICONIC_LAUNCHER_PARAMS"

LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$DIR_RECIPES_PROJECT/$FILE_RECIPES_PROJECT_PRE_OPEN" \
  "$DIR_RECIPES_PROJECT_FULL/$FILE_RECIPES_PROJECT_PRE_OPEN"

LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$DIR_RECIPES_PROJECT/$FILE_RECIPES_PROJECT_PROJECT_PRE_OPEN" \
  "$DIR_RECIPES_PROJECT_FULL/$FILE_RECIPES_PROJECT_PROJECT_PRE_OPEN"

LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$DIR_RUN_TEST/$FILE_RUN_TEST_MAIN" \
  "$DIR_RUN_TEST_FULL/$FILE_RUN_TEST_MAIN"

LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$DIR_RUN_ICONIC/$FILE_RUN_ICONIC_ICONIFY" \
  "$DIR_RUN_ICONIC_FULL/$FILE_RUN_ICONIC_ICONIFY"

LINK_FILE_TO_DESTINATION "$SUBMODULES_HOME/$DIR_RUN_PROJECT/$FILE_RUN_PROJECT_OPEN" \
  "$DIR_RUN_PROJECT_FULL/$FILE_RUN_PROJECT_OPEN"